export const COMPANY_LEGAL_NAME = "CODEVERSE SERVIÇOS DE TECNOLOGIA LTDA";
export const COMPANY_CNPJ = "59.161.274/0001-05";
export const COMPANY_LEGAL_IDENTIFICATION = `${COMPANY_LEGAL_NAME} · CNPJ ${COMPANY_CNPJ}`;
